# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kernel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckernel.proto\x12\x07jupyter\"\x1e\n\x0e\x45xecuteRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"l\n\x0f\x45xecuteResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.jupyter.ExecuteStatus\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.jupyter.OutputType\x12\x0e\n\x06output\x18\x03 \x01(\t\"\x0f\n\rCancelRequest\"\x10\n\x0e\x43\x61ncelResponse\"1\n\x11\x43ompletionRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\x05\"%\n\x12\x43ompletionResponse\x12\x0f\n\x07matches\x18\x01 \x03(\t\"\x0f\n\rStatusRequest\"7\n\x0eStatusResponse\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.jupyter.KernelStatus\"\r\n\x0bStopRequest\"\x0e\n\x0cStopResponse*\'\n\rExecuteStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01*)\n\x0cKernelStatus\x12\x0c\n\x08STARTING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01*\\\n\nOutputType\x12\x08\n\x04TEXT\x10\x00\x12\x07\n\x03PNG\x10\x01\x12\x08\n\x04JPEG\x10\x02\x12\x08\n\x04HTML\x10\x03\x12\x07\n\x03SVG\x10\x04\x12\x08\n\x04JSON\x10\x05\x12\t\n\x05LaTeX\x10\x06\x12\t\n\x05\x43LEAR\x10\x07\x32\xc9\x02\n\rJupyterKernel\x12@\n\x07\x65xecute\x12\x17.jupyter.ExecuteRequest\x1a\x18.jupyter.ExecuteResponse\"\x00\x30\x01\x12\x45\n\x08\x63omplete\x12\x1a.jupyter.CompletionRequest\x1a\x1b.jupyter.CompletionResponse\"\x00\x12;\n\x06\x63\x61ncel\x12\x16.jupyter.CancelRequest\x1a\x17.jupyter.CancelResponse\"\x00\x12;\n\x06status\x12\x16.jupyter.StatusRequest\x1a\x17.jupyter.StatusResponse\"\x00\x12\x35\n\x04stop\x12\x14.jupyter.StopRequest\x1a\x15.jupyter.StopResponse\"\x00\x42U\n-org.apache.zeppelin.interpreter.jupyter.protoB\x12JupyterKernelProtoP\x01\xa2\x02\rJupyterKernelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kernel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-org.apache.zeppelin.interpreter.jupyter.protoB\022JupyterKernelProtoP\001\242\002\rJupyterKernel'
  _EXECUTESTATUS._serialized_start=397
  _EXECUTESTATUS._serialized_end=436
  _KERNELSTATUS._serialized_start=438
  _KERNELSTATUS._serialized_end=479
  _OUTPUTTYPE._serialized_start=481
  _OUTPUTTYPE._serialized_end=573
  _EXECUTEREQUEST._serialized_start=25
  _EXECUTEREQUEST._serialized_end=55
  _EXECUTERESPONSE._serialized_start=57
  _EXECUTERESPONSE._serialized_end=165
  _CANCELREQUEST._serialized_start=167
  _CANCELREQUEST._serialized_end=182
  _CANCELRESPONSE._serialized_start=184
  _CANCELRESPONSE._serialized_end=200
  _COMPLETIONREQUEST._serialized_start=202
  _COMPLETIONREQUEST._serialized_end=251
  _COMPLETIONRESPONSE._serialized_start=253
  _COMPLETIONRESPONSE._serialized_end=290
  _STATUSREQUEST._serialized_start=292
  _STATUSREQUEST._serialized_end=307
  _STATUSRESPONSE._serialized_start=309
  _STATUSRESPONSE._serialized_end=364
  _STOPREQUEST._serialized_start=366
  _STOPREQUEST._serialized_end=379
  _STOPRESPONSE._serialized_start=381
  _STOPRESPONSE._serialized_end=395
  _JUPYTERKERNEL._serialized_start=576
  _JUPYTERKERNEL._serialized_end=905
# @@protoc_insertion_point(module_scope)
